spring:
 resources:
  #告诉springboot到哪里去找页面资源
  static-locations: classpath:/static
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
  username: root
  password: root
  druid:
   # 初始化连接大小[0]
   initial-size: 1
   # 最小空闲连接数[0]
   min-idle: 1
   # 最大连接数[8]
   max-active: 20
   # 配置获取连接等待超时的时间(毫秒)[-1]
   max-wait: 60000
   # 查询超时时间(秒)
   query-timeout: 60
   # 用来检测连接是否有效的sql，要求是一个查询语句
   validation-query: SELECT 'x'
   # 申请连接时检测连接可用性[false]
   test-on-borrow: false
   # 归还连接检测[false]
   test-on-return: false
   # 超时是否检测连接可用性[true]
   test-while-idle: true
   # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接 (毫秒)
   time-between-eviction-runs-millis: 60000
   #  配置一个连接在池中最小生存的时间(毫秒，默认30分钟)
   min-evictable-idle-time-millis: 300000
   # 通过别名的方式配置扩展插件，常用的插件有：监控统计用的filter:stat；日志用的filter:log4j；防御sql注入的filter:wall
   filters: stat,wall,slf4j
   # 合并多个DruidDataSource的监控数据
   use-global-data-source-stat: true
   filter:
    stat:
     merge-sql: false
     db-type: mysql
     slow-sql-millis: 2000
     log-slow-sql: true
    wall:
     db-type: mysql
     config:
      drop-table-allow: false
      delete-allow: false
      enabled: true
   web-stat-fileter:
    url-pattern: /*
    exclusions: \*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
    enabled: true
   stat-view-servlet:
    url-pattern: /druid/*
    login-password: admin
    reset-enable: false
    login-username: admin
    enabled: true

 cache:
  type: redis
 redis:
  host: localhost
  port: 6379
  password:
  database: 5
  jedis:
   pool:
    max-idle: 8
    min-idle: 0
    max-active: 8
    max-wait: -1ms

mapper:
  identity: MYSQL
  not-empty: false
  mappers: com.zykspring.funnycore.base.Mapper

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:**/*Mapper.xml
  type-aliases-package: com.zykspring.funnycore.system.dto

server.port: 9090

